spring.datasource.url=jdbc:h2:mem:funkostore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.main.web-application-type=servlet
# Ajustar origenes permitidos si se despliega a otro host
funkostore.cors.allowed-origins=http://localhost:5173,http://localhost:5174
app.jwt.secret=JCelcolombianoqueLogratodo_SecretoUltraLargo_1234567890abcd
app.jwt.expiration=900000
